# fly.toml app configuration file generated for david-inventory-app on 2023-08-15T12:47:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "david-inventory-app"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
